linters:
  disable-all: true
  enable:
    - errorlint
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - revive
    - typecheck
    - unconvert
    - unparam
    - unused
issues:
  max-per-linter: 0
  max-same-issues: 0
run:
  build-tags:
    - integration
  deadline: 5m
