linters:
  disable-all: true
  enable:
    - errcheck
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - revive
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused
linters-settings:
  gosec:
    excludes:
      - G306
  revive:
    rules:
      - name: unused-parameter
        disabled: true
issues:
  max-per-linter: 0
  max-same-issues: 0
run:
  build-tags:
    - integration
  deadline: 5m
