on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        protoc-version: ['3.5.0', '3.6.0', '3.17.0']
    env:
      GOPATH: ${{ github.workspace }}
      GOBIN: ${{ github.workspace }}/bin
    defaults:
      run:
        working-directory: ${{ env.GOPATH }}/src/github.com/lyft/protoc-gen-star
    name: protoc version ${{ matrix.protoc-version }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          path: ${{ env.GOPATH }}/src/github.com/lyft/protoc-gen-star
      - name: Set Up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.14.6'
      - run: mkdir -p $GOPATH/bin
      - run: wget "https://github.com/protocolbuffers/protobuf/releases/download/v${{ matrix.protoc-version }}/protoc-${{ matrix.protoc-version }}-linux-x86_64.zip" -O /tmp/protoc.zip
      - run: unzip /tmp/protoc.zip -d /tmp
      - run: sudo mv /tmp/bin/protoc /usr/local/bin/protoc
      - run: sudo mv /tmp/include/google /usr/local/include/google
      - name: Generate Testdata
        run: make testdata
      - name: Lint
        run: make lint tests
